algoritmo "exercicio 8"
// Função :
// Autor :
// Data : 25/09/2025
// Seção de Declarações 
var
      cotacao, qtdDolar, valorReal: real
inicio

  escreval("===== Conversor de Dólar para Real =====")
   escreva("Digite a cotação do dólar (R$): ")
   leia(cotacao)

   escreva("Digite a quantidade de dólares (US$): ")
   leia(qtdDolar)

   valorReal <- cotacao * qtdDolar

   escreval("O valor em reais é: R$ ", valorReal:0:2)
// Seção de Comandos 
fimalgoritmo
