algoritmo "semnome"
// Função : fala qual numero e maior que o outro
// Autor :
// Data : 29/09/2025
// Seção de Declarações 
var
n1, n2 : inteiro
inicio
escreva(" digite o numero 1 :")
leia(n1)
escreva(" digite o numero 2 :")
leia(n2)
se n1 > n2 entao
escreval (" n1 é maior que n2 ")
fimse
se n2 < n1 entao
escreval (" n2 é menor que n1 ")
fimse
se n2 > n1 entao
escreval (" n2 é maior que n1
.  ")
fimse



// Seção de Comandos 
fimalgoritmo


