algoritmo "ex18"
funcao: esse alg serve para mostrar se a pessoa e menor de idade ou maior
var
x, idade: inteiro

inicio
// Seção de Comandos
para x de 1 ate 75 faca
     escreva("Digite a idade: ")
     leia(idade)
     se idade >= 18 entao
        escreval("a pessoa é maior de idade!")
        
        senao se idade <= 18 entao
         escreval(" a pessoa é menor de idade ")
 fimse
fimpara
 
fimalgoritmo


