algoritmo "exercicio 6"
// Função :
// Autor :
// Data : 25/09/2025
// Seção de Declarações 
var
  A,B, TEMP : inteiro
inicio
escreval("digite ovalor A : ")
leia(A)
escreval("digite ovalor B : ")
leia(B)
escreval("o valor de A é :", A)
escreval("o valor de B é :", B)
escreval(" Efetuando a troca ")
TEMP<-A
A<-B
B<-TEMP
escreval("o valor de A é :", A)
escreval("o valor de B é :", B)


// Seção de Comandos 
fimalgoritmo
